#!/bin/bash
FILE="data.json"
NAME=$(jq -r '.name' "$FILE" | sed 's/.*/\u&/') #capitalize first letter
HEIGHT=$(jq -r '.height' "$FILE" | awk '{printf "%.1f",$1/10}') #convert decimeter to meters
WEIGHT=$(jq -r '.weight' "$FILE" | awk '{printf "%.0f",$1/10}') # Convert hectograms to kg
TYPES=$(jq -r '.types[].type.name' "$FILE" | sed 's/.*/\u&/' | paste -sd "/" -) #join multiple types
echo "$NAME is a type of $TYPES, weights ${WEIGHT}kg, and is ${HEIGHT}m takk"

